### ISSUE TITLE
How about adding a space into div.content

### ISSUE THREAD

**Issue by Hy369** [gawth/wiki#1]
The div.content is too close to side menu. How about adding a space into div.content?
```
.content {
    margin: 0 auto;
    padding: 0 2em;
    margin-left: 160px;  // <--- eg: change  150 to 160
    margin-bottom: 50px;
    line-height: 1.4em;
}
```

Second, the div.wikiBody unable to display full with of parent.

```
.wikiBody {
    background: aliceblue;
    padding: 5px;
    display: inline-block;  // <-- The css caused this problem.
}
```

**Comment by gawth** [comment]
Sorry, been on holiday so didnt see your issue.  I'll take a look - sounds fine.
Alan

**Comment by gawth** [comment]
Changes made an pushed up to master.  Looks better - thanks.  As you can tell, CSS is not my strong point :-)
